<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Chuong4_Bai4_PhongKhamMDI</RootNamespace>
    <AssemblyName>Chuong4_Bai4_PhongKhamMDI</AssemblyName>
    <ApplicationDefaultFont>Segoe UI, 9pt</ApplicationDefaultFont>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

</Project>
